### ISSUE TITLE
Remove from ZF2?

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/ZendXml#10]
Why was ZendXml added to ZF 2.5?
https://github.com/zendframework/zf2/blob/release-2.5.0/composer.json#L64

Is was never served with ZF2 before

**Comment by weierophinney** [comment]
Yes, it was. We added it to fix [ZF2014-01](http://framework.zend.com/security/advisory/ZF2014-01), and ZendXml has been included with ZF2 (via Composer) since 2.1.6 and 2.2.6.

**Comment by ThaDafinser** [comment]
Okay, didnt saw that :see_no_evil: 

https://github.com/zendframework/zf2/blob/release-2.1.6/composer.json#L13
